export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {/* VAG Rundschrift */}
      {/* <link rel="stylesheet" href="https://use.typekit.net/gbc3qst.css"></link> */}
    </>
  );
}
